import type { Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { requirePermission } from "../rbac/authorize";
import { writeAudit } from "../audit/audit";
import { ValidationFailedError } from "../errors";
import { getOrCreateLatestRulesVersion } from "./rules-version";

// Авто-раскладка сетки раундов+заездов дивизиона по справочнику этапов
// (docs/00_DECISIONS.md, A7). Явное действие организатора (кнопка
// "Сгенерировать раунды"), не происходит само по себе. После генерации
// обычные "добавить раунд"/"добавить заезд" остаются доступны для ручной
// правки — это не единственный способ управления сеткой, только стартовая
// раскладка.
export async function generateRounds(divisionId: string): Promise<{ createdRoundIds: string[] }> {
  const division = await prisma.division.findUniqueOrThrow({
    where: { id: divisionId },
    select: { id: true, competitionId: true, heatCapacity: true },
  });
  const actor = await requirePermission("round:create", division.competitionId);

  const eligibleWhere: Prisma.RegistrationWhereInput = {
    divisionId,
    status: "REGISTERED",
    checkIn: { is: { status: { in: ["CHECKED_IN", "LATE"] } } },
  };
  const [leaderCount, followerCount, stages, existingRoundsCount] = await Promise.all([
    prisma.registration.count({ where: { ...eligibleWhere, role: "LEADER" } }),
    prisma.registration.count({ where: { ...eligibleWhere, role: "FOLLOWER" } }),
    prisma.roundStageCatalog.findMany({ where: { isActive: true }, orderBy: { order: "asc" } }),
    prisma.round.count({ where: { divisionId } }),
  ]);

  if (stages.length === 0) {
    throw new ValidationFailedError(
      "В справочнике этапов отбора нет ни одного активного этапа — сначала настройте справочник."
    );
  }
  const pool = Math.max(leaderCount, followerCount);
  if (pool === 0) {
    throw new ValidationFailedError(
      "В дивизионе нет ни одного участника, прошедшего check-in — генерировать сетку пока не из чего."
    );
  }

  // Этап пропускаем, если в него и так проходит не меньше, чем сейчас
  // осталось (создавать такой раунд бессмысленно) — кроме последнего этапа
  // в справочнике (обычно "Финал"), он создаётся всегда, что бы ни осталось.
  type Plan = { stageId: string; stageName: string; finalistsCount: number; poolAtStart: number };
  const plan: Plan[] = [];
  let remaining = pool;
  stages.forEach((stage, i) => {
    const isLast = i === stages.length - 1;
    if (!isLast && remaining <= stage.defaultAdvanceCount) return;
    plan.push({ stageId: stage.id, stageName: stage.name, finalistsCount: stage.defaultAdvanceCount, poolAtStart: remaining });
    remaining = stage.defaultAdvanceCount;
  });

  const createdRoundIds = await prisma.$transaction(async (tx) => {
    const rules = await getOrCreateLatestRulesVersion(tx, division.competitionId, actor);
    const ids: string[] = [];

    for (const [i, step] of plan.entries()) {
      const order = existingRoundsCount + i + 1;
      const round = await tx.round.create({
        data: {
          divisionId,
          stageId: step.stageId,
          order,
          finalistsCount: step.finalistsCount,
          rulesId: rules.id,
        },
      });
      ids.push(round.id);

      await writeAudit(tx, {
        actor,
        action: "round.create",
        entityType: "Round",
        entityId: round.id,
        after: {
          divisionId,
          stageId: step.stageId,
          stageName: step.stageName,
          order,
          finalistsCount: step.finalistsCount,
          rulesId: rules.id,
          autoGenerated: true,
        },
      });

      const heatCount = Math.ceil(step.poolAtStart / division.heatCapacity);
      for (let number = 1; number <= heatCount; number++) {
        const heat = await tx.heat.create({ data: { roundId: round.id, number } });
        await writeAudit(tx, {
          actor,
          action: "heat.create",
          entityType: "Heat",
          entityId: heat.id,
          after: { roundId: round.id, number, autoGenerated: true },
        });
      }
    }

    await writeAudit(tx, {
      actor,
      action: "division.generate_rounds",
      entityType: "Division",
      entityId: divisionId,
      after: { leaderCount, followerCount, createdRoundIds: ids, stagesUsed: plan.map((p) => p.stageName) },
    });

    return ids;
  });

  return { createdRoundIds };
}
