import { prisma } from "@/lib/prisma";
import { requirePermission } from "../rbac/authorize";
import { writeAudit } from "../audit/audit";
import { ValidationFailedError } from "../errors";
import { getOrCreateLatestRulesVersion } from "./rules-version";

// Авто-раскладка сетки раундов+заездов дивизиона по ПЛАНУ этого дивизиона
// (docs/00_DECISIONS.md, A14) — план "сколько пар участвует в каждом этапе"
// задаётся один раз при создании дивизиона (DivisionStagePlan) и дальше не
// меняется; раньше (A7) раунды раскладывались сравнением живых чисел
// регистраций с общим RoundStageCatalog.defaultAdvanceCount — теперь
// используется явный план организатора, живые числа не участвуют в расчёте
// (только показываются рядом для сверки, до генерации). Явное действие
// организатора (кнопка "Сгенерировать раунды"), не происходит само по себе.
export async function generateRounds(divisionId: string): Promise<{ createdRoundIds: string[] }> {
  const division = await prisma.division.findUniqueOrThrow({
    where: { id: divisionId },
    select: { id: true, competitionId: true, heatCapacity: true },
  });
  const actor = await requirePermission("round:create", division.competitionId);

  const [plan, existingRoundsCount] = await Promise.all([
    prisma.divisionStagePlan.findMany({
      where: { divisionId },
      include: { stage: true },
      orderBy: { stage: { order: "asc" } },
    }),
    prisma.round.count({ where: { divisionId } }),
  ]);

  if (plan.length === 0) {
    throw new ValidationFailedError(
      "Для этого дивизиона не задан план по этапам («сколько пар участвует в каждом раунде») — он настраивается один раз при создании дивизиона."
    );
  }

  // finalistsCount раунда этапа X = participantCount СЛЕДУЮЩЕГО по порядку
  // этапа плана (сколько проходит из X в X+1); у последнего этапа плана
  // следующего нет — число идёт как есть (сколько мест/победителей).
  type Step = { stageId: string; stageName: string; participantCount: number; finalistsCount: number };
  const steps: Step[] = plan.map((p, i) => ({
    stageId: p.stageId,
    stageName: p.stage.name,
    participantCount: p.participantCount,
    finalistsCount: i < plan.length - 1 ? plan[i + 1].participantCount : p.participantCount,
  }));

  const createdRoundIds = await prisma.$transaction(async (tx) => {
    const rules = await getOrCreateLatestRulesVersion(tx, division.competitionId, actor);
    const ids: string[] = [];

    for (const [i, step] of steps.entries()) {
      const order = existingRoundsCount + i + 1;
      const round = await tx.round.create({
        data: {
          divisionId,
          stageId: step.stageId,
          order,
          finalistsCount: step.finalistsCount,
          rulesId: rules.id,
        },
      });
      ids.push(round.id);

      await writeAudit(tx, {
        actor,
        action: "round.create",
        entityType: "Round",
        entityId: round.id,
        after: {
          divisionId,
          stageId: step.stageId,
          stageName: step.stageName,
          order,
          participantCount: step.participantCount,
          finalistsCount: step.finalistsCount,
          rulesId: rules.id,
          autoGenerated: true,
        },
      });

      const heatCount = Math.ceil(step.participantCount / division.heatCapacity);
      for (let number = 1; number <= heatCount; number++) {
        const heat = await tx.heat.create({ data: { roundId: round.id, number } });
        await writeAudit(tx, {
          actor,
          action: "heat.create",
          entityType: "Heat",
          entityId: heat.id,
          after: { roundId: round.id, number, autoGenerated: true },
        });
      }
    }

    await writeAudit(tx, {
      actor,
      action: "division.generate_rounds",
      entityType: "Division",
      entityId: divisionId,
      after: { createdRoundIds: ids, stagesUsed: steps.map((s) => s.stageName) },
    });

    return ids;
  });

  return { createdRoundIds };
}
